version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminsecret
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password']

  redis:
    image: redis:7.4
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: clwy1234
volumes:
  mysql-data:
